---
- name: Setup Ubuntu Server with PM2 and Nginx
  hosts: all
  become: true
  vars:
    nodejs_version: "16"  # Change to your desired Node.js version
    app_name: "data-ingestion-demo"    # Name of your Node.js app
    app_port: 3000        # Local port where the Node.js app runs
    domain_name: "127.0.0.1"  # Replace with your domain or server IP

  tasks:
    # Update and upgrade system packages
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    # Install required dependencies
    - name: Install required dependencies
      apt:
        name:
          - curl
          - nginx
        state: present

    # Install Node.js
    - name: Add Node.js APT repository
      command: curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | bash -
      args:
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    # Install pm2 globally
    - name: Install pm2 process manager
      npm:
        name: pm2
        global: yes

    # Create a directory for the app (optional)
    - name: Create application directory
      file:
        path: "/home/ubuntu/{{ app_name }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    # Configure pm2 to manage the app
    - name: Setup pm2 to manage the app
      shell: |
        pm2 start app.js --name "{{ app_name }}" --watch
        pm2 save
        pm2 startup systemd
      args:
        chdir: "/home/ubuntu/{{ app_name }}"
      register: pm2_output

    - name: Display pm2 setup output
      debug:
        var: pm2_output.stdout

    # Configure nginx
    - name: Configure nginx for reverse proxy
      template:
        src: templates/nginx.j2
        dest: "/etc/nginx/sites-available/{{ app_name }}"
        owner: root
        group: root
        mode: 0644

    - name: Enable nginx site configuration
      file:
        src: "/etc/nginx/sites-available/{{ app_name }}"
        dest: "/etc/nginx/sites-enabled/{{ app_name }}"
        state: link

    - name: Remove default nginx site configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx to apply changes
      service:
        name: nginx
        state: restarted

    # Secure server
    - name: Enable UFW and allow HTTP
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Enable UFW and deny all incoming except allowed
      ufw:
        state: enabled
        policy: deny
